version: "2.4"
services:
  cephadm-host-base:
    build:
      context: .
    environment:
      - CEPH_BRANCH=master
    image: cephadm-box
    # probably not needed with rootless Docker and cgroups v2
    # privileged: true
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - SYS_TIME
      - SYS_RAWIO
      - MKNOD
      - NET_RAW
      - SETUID
      - SETGID
      - CHOWN
      - SYS_PTRACE
      - SYS_TTY_CONFIG
      - CAP_AUDIT_WRITE
      - CAP_AUDIT_CONTROL
    stop_signal: RTMIN+3
    volumes:
      - ../../../:/ceph:z
      - ..:/cephadm:z
      # - ./daemon.json:/etc/docker/daemon.json
      # dangerous, maybe just map the loopback
      # https://stackoverflow.com/questions/36880565/why-dont-my-udev-rules-work-inside-of-a-running-docker-container
      - /run/udev:/run/udev
      - /sys/dev/block:/sys/dev/block
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /dev/fuse:/dev/fuse
      - /dev/disk:/dev/disk
      - /dev/mapper:/dev/mapper
      - /dev/mapper/control:/dev/mapper/control
    mem_limit: "20g"
    scale: -1
  seed:
    extends:
      service: cephadm-host-base
    ports:
      - "2222:22"
      - "3000:3000"
      - "8888:8888"
      - "8443:8443"
      - "9095:9095"
    scale: 1
  hosts:
    extends:
      service: cephadm-host-base
    scale: 1


volumes:
  var-lib-docker:

network_mode: public
